### PR TITLE
jq: new package

### PR DESCRIPTION
**Pull request by encounter**
https://stedolan.github.io/jq/

### CODE REVIEW

**Comment by ryzhovau** [comment]
Looks fine, thanks!

**Comment by lstreet-aquent** [comment]
Should this be contributed to openwrt/packages instead?

**Comment by ryzhovau** [comment]
I was looking for the console JSON parser recenlty, so I'll gladly add this package to our own feed. Just let us finish monthly sync with upstream in the next few days.

OpenWrt will accept your PR only if you'll be maintainer of this package. You may do that a bit later, after `jq` will be proven as working in Entware.

**Comment by ryzhovau** [comment]
[Done](https://github.com/Entware-ng/rtndev/commit/58c3f30851282001ad318adb9922b52dbbb7127d). Thank you!

**Pull request closed without merging**
